### ISSUE TITLE
Multi event - Purchase

### ISSUE THREAD

**Issue by SamuelBreton** [at-internet/gtm-pa-tagging#1]
Hello BenDz,

Lors d'un a achat, on va souvent voir un dataLayer comme celui ci composé d'un event et d'un tableau d'items du panier. https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?client_type=gtm#make_a_purchase_or_issue_a_refund

Dans GA4, (Par exemple), on envoie uniquement l'évent purchase, avec items en paramètre qui est le tableau des produits.

Dans la doc Piano, il faut trigger plusieurs events CF : https://developers.atinternet-solutions.com/piano-analytics/data-collection/how-to-send-events/sales-insights#transactionconfirmation-and-productpurchased
En gros : transaction.confirmation et autant de fois product.purchased qu'il y a de produits.

Via une intégration en HTML, on peut faire simplement boucler sur l'ensemble des produits pour faire un pa.sendEvents() avec tous les events.

J'ai un peu de mal a voir comment le faire avec le template qui permet d'envoyer un seul event à la fois et surtout avoir la totalité des items.

Un grand merci.

**Comment by BenDz** [comment]
Hello @SamuelBreton.
Désolé pour le délai. On a bien noté le sujet, et on essaye de le prioriser rapidement.

**Comment by BenDz** [comment]
Hello @SamuelBreton 
Nous avons intégré un module de bridge dans le template, qui traduit automatiquement les events ecommerce GA4 vers des events Piano.
