### ISSUE TITLE
Tagging does not work anymore since the newest update

### ISSUE THREAD

**Issue by DMJulie** [at-internet/gtm-pa-tagging#7]
Hi BenDz,

firstly I'd like to thank you for your great work making this GTM template accessible to everyone.

The template is great & everything worked perfectly fine until now but somehow the tagging does not work anymore since the newest update (e.g. no push of piano snippet). There are no hits sent even tho there weren't any changes in the gtm-tags. I tried the old template on antoher gtm-container, where I haven't updated the template yet and everything works fine and the hits are sent & the piano snippet is integrated to the website code. 

Do you know if there were any changes in the template-update that causes this issue & if there's a possible fix?

Best regards, 
Julie

**Comment by BenDz** [comment]
Hi @DMJulie and thanks for your feedback!
Could you tell us more about your configuration: what kind of method are you using? (`Send an event` or `Send multiple events`). With the multiple events one, we now check if the event name is defined before pushing it, that's the only change regarding event sending, but this could also be a side effect of another update.
If you can share with me your GTM configuration or a page where I could test your case to benjamin.diolez@piano.io

Thanks
